services:
  api1:
    build: .
    command: ["/bin/api.exe"]
    environment:
      - REFERENCES_PATH=/app/data/references_small.json
      - TIMING_ENABLED=true
      - TIMING_FILE=/tmp/timings.log
    volumes:
      - ./data:/app/data:ro
    expose:
      - "9999"
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "159MB"

  api2:
    build: .
    command: ["/bin/api.exe"]
    environment:
      - REFERENCES_PATH=/app/data/references_small.json
      - TIMING_ENABLED=true
      - TIMING_FILE=/tmp/timings.log
    volumes:
      - ./data:/app/data:ro
    expose:
      - "9999"
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "159MB"

  lb:
    image: haproxy:alpine
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "32MB"
